In [1]:
import numpy as np

In [2]:
a=[1,2,3,4,5]

## ndarray object

In [4]:
print(a)

[1, 2, 3, 4, 5]


In [5]:
print(type(a))

<class 'list'>


In [6]:
np_a=np.array(a)

In [7]:
print(np_a)

[1 2 3 4 5]


In [8]:
print(type(np_a))

<class 'numpy.ndarray'>


In [9]:
#python list 
L= range(100)
%timeit [i**2 for i in L]

4.37 µs ± 220 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [10]:
a=np.arange(1000)
%timeit a**2

1.65 µs ± 558 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## Creating arrays(Manually crating arrays)
# 1-D


In [12]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [13]:
#print dimension 
a.ndim

1

In [14]:
#Shape
a.shape

(4,)

In [15]:
#2-D
b= np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
b.ndim

2

In [17]:
b.shape

(2, 3)

In [18]:
# 3D
c = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
c.ndim

3

In [20]:
c.shape 

(2, 2, 2)

# Creating NumPy Arrays From a list

In [22]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [23]:
np.array(my_list)

array([1, 2, 3])

In [24]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [25]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.array(matrix).shape

(3, 3)

# a range

In [28]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
h=np.arange(1,10,3)
h

array([1, 4, 7])

## Linespace

In [31]:
a=np.linspace(0,5,6)
a

array([0., 1., 2., 3., 4., 5.])

In [32]:
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

## Zeros

In [34]:
q=np.zeros((2,3))
q

array([[0., 0., 0.],
       [0., 0., 0.]])

# ones

In [36]:
a=np.ones((4,3))     #in this condition there are 4 arrays and 3 columns.
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# eye

In [38]:
c = np.eye(3)    ## 3*3 matrix if user put 2 then 2*2 matrix will be show
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
d=np.eye(3,2)    #3 is number of rowsand 2 number of column 
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [40]:
a = np.diag([7,9,8,5])
a

array([[7, 0, 0, 0],
       [0, 9, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 5]])

In [41]:
np.diag(a)         # Extract Diagonal

array([7, 9, 8, 5])

### Random --> Numpy also has lots of ways to create random number arrays :


In [43]:
ran = np.random.randint(1,121,5)
print(ran)

[75 42 77 69 93]


In [44]:
a = np.random.rand(4)
a

array([0.54586152, 0.52500283, 0.9232145 , 0.05053279])

In [45]:
# randn -- return a sample(or samples )from the 'standard normal' distribution.***Gausian***

In [46]:
a = np.random.randn(100)
a

array([ 0.52897644, -1.01717665,  1.07675825,  0.15507863, -0.40740848,
        0.63309592,  1.15017462, -0.85948493,  0.15841414,  0.70172306,
        1.31921173, -1.01822792, -1.40757041, -1.32774807, -0.15093455,
        1.37024057,  0.95581345, -0.28722272, -0.92313706, -0.64249114,
       -0.21307425, -0.84662438, -1.07455021, -0.88636425, -2.24119756,
       -0.11375307,  0.69184318, -0.75589835, -1.14911206,  0.22059275,
       -0.8382538 ,  0.29518786,  2.10980831,  0.70738754, -0.29666207,
       -1.01255161,  0.67278495,  0.55477068,  0.46988278, -0.23517478,
       -0.14717925,  0.08275124, -0.50242727,  1.0095391 , -0.83251099,
        0.10471304,  0.03226679,  1.00916207, -0.85107812, -0.85546534,
       -0.27251898,  0.26487625,  1.1771816 , -0.79098488, -0.91562803,
       -0.08751646, -0.83137276, -0.74748986, -0.95612646, -0.83329042,
       -1.73111295, -1.28809604, -0.95105019, -2.27952289, -0.48554258,
       -0.13913393,  0.46145049,  0.468687  ,  0.69765312, -0.68

# Copy Array

In [48]:
a1 = np.array([1,2,3,4])
b1= a1
b1[0]= 200
print(a1)
print(b1)

[200   2   3   4]
[200   2   3   4]


## Reshape array

In [50]:
ar = np.arange(25)
print(ar)
print(ar.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


In [51]:
a1=ar.reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
import numpy as np
k=np.array([[1,3],[4,6],[7,9]])
print(k)
print("Shape of k:{}".format(k.shape))

[[1 3]
 [4 6]
 [7 9]]
Shape of k:(3, 2)


In [53]:
## reshaping 
b=k.reshape(2,3)
print(b)
print("shape of b:{}".format(b.shape))

[[1 3 4]
 [6 7 9]]
shape of b:(2, 3)


# Transpose array

In [55]:
ap=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Shape:{}".format(ap.shape))
print(ap)

Shape:(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
c=ap.T
print(c)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Flattening

In [58]:
N= np.array([[1,2,3],[4,5,6]])       ##
N.ravel()

array([1, 2, 3, 4, 5, 6])

In [59]:
c.ravel()     ## in this part c is defined and then c value is declare for separed by comma 

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

# Sorting

In [61]:
a = np.array([[8,3,6],[2,8,2]])
b=np.sort(a,axis=0)     ##
b

array([[2, 3, 2],
       [8, 8, 6]])

In [62]:
a = np.array([[8,3,6],[2,8,2]])    ##
b=np.sort(a,axis=1)
b

array([[3, 6, 8],
       [2, 2, 8]])

# Add/Remove operattions on a numpy

In [64]:
h=np.array([4,8,6])               ## Adding value 
h=np.append(h,[2,4,5])
print("Numpy array after addition:",h)

Numpy array after addition: [4 8 6 2 4 5]


In [65]:
h=np.delete(h,2)
print("Numpy array after delettion of one element",h)

Numpy array after delettion of one element [4 8 2 4 5]


# Indexing

In [67]:
s=np.diag([1,2,5])
# print(s)
print(s[2,1])

0


In [68]:
s[2,1]=4    ##
s


array([[1, 0, 0],
       [0, 2, 0],
       [0, 4, 5]])

# Slicing 

In [83]:
ak=np.arange(4,19)
ak

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [85]:
ak[1:10:4]


array([ 5,  9, 13])

In [87]:
ak=np.arange(11)
ak[5:]

array([ 5,  6,  7,  8,  9, 10])

In [73]:
ak=np.arange(11)
ak

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
ak[6:]=10                          ###in 6 index position then start with10
ak

array([ 0,  1,  2,  3,  4,  5, 10, 10, 10, 10, 10])

In [90]:
ak[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# Fancy Indexing 

In [118]:
a=np.random.randint(0,20,5)
a

array([14, 16, 19, 13, 14])

In [120]:
a[a % 2 == 0]


array([14, 16, 14])

In [122]:
a[a % 2 == 0]=-1
a

array([-1, -1, 19, 13, -1])

# Indexing with an array of integer 

In [127]:
a=np.arange(0,101,10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [131]:
a[[2,3,5,4,8]]

array([20, 30, 50, 40, 80])

In [135]:
a[[9,7]]=-200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200,  100])

# Operation 

### with scalars

In [138]:
a=np.array([1,2,3,4])
print(a)
print(a+1)

[1 2 3 4]
[2 3 4 5]


In [140]:
a**2

array([ 1,  4,  9, 16])

### All Arithematic operators 

In [155]:
n= np.ones(4)+1
n

array([2., 2., 2., 2.])

In [157]:
a-n

array([-1.,  0.,  1.,  2.])

In [159]:
a*n

array([2., 4., 6., 8.])

In [161]:
g=np.array([[1,2],[3,4],[5,6]])
h=np.array([[4,4],[4,4],[4,4]])
print("sum of g and h is :\n",g+h)

sum of g and h is :
 [[ 5  6]
 [ 7  8]
 [ 9 10]]


In [163]:
print("multiplication of g and h is :\n",g*h)

multiplication of g and h is :
 [[ 4  8]
 [12 16]
 [20 24]]


In [165]:
c=np.diag([1,2,3,4])
print(c*c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [167]:
## Matrix multiplication 
a= np.array([[1,2,1],[3,4,3],[5,6,5]])
b=np.array([[4,4,1],[4,4,2],[4,4,3]])
print(np.matmul(a,b))

[[16 16  8]
 [40 40 20]
 [64 64 32]]


### Comparision 

In [170]:
a =np.array([1,2,3,4])
b=np.array([5,2,1,4])
a==b

array([False,  True, False,  True])

In [172]:
a>b

array([False, False,  True, False])

In [174]:
a<b

array([ True, False, False, False])

In [192]:
a =np.array([1,2,3,4])
b=np.array([1,2,3,4])
c=np.array([5,6,7,6])

In [194]:
np.array_equal(a,b)

True

In [196]:
np.array_equal(a,c)

False

#### Logical Operator

In [201]:
a= np.array ([1,1,0,0])
b= np.array ([1,0,1,0])
print(np.logical_or(a,b))
a= np.array ([1,1,0,0])
b= np.array ([1,0,1,0])
print(np.logical_and(a,b))

[ True  True  True False]
[ True False False False]


In [203]:
a= np.array ([1,1,0,0],dtype=int)
b= np.array ([1,0,1,0],dtype=int)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [205]:
a= np.array ([1.25,2.6,3.1,4.5],dtype=float)
b= np.array ([1.2,5.3,9.1,7.6],dtype=float)
a+b

array([ 2.45,  7.9 , 12.2 , 12.1 ])


### Transcendental functions 

In [211]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [213]:
np.log(a)

C:\Users\suven\AppData\Local\Temp\ipykernel_16416\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [215]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

## Basics Reductions

In [220]:
x=np.array([[1,3,2],[5,4,8]])
np.sum(x)

23

In [222]:
x=np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [224]:
x.sum(axis=1)

array([2, 4])

In [226]:
x.sum (axis=0)

array([3, 3])

In [228]:
x=np.array([1,5,8,5,6,7,2,3,9])
x

array([1, 5, 8, 5, 6, 7, 2, 3, 9])

In [230]:
x.argmin()

0

In [232]:
x.argmax()

8

In [15]:
import numpy as np
normal_array=np.arange(0,10,1)
print('array is',format(normal_array))

## Min
print('min element is ',np.min(normal_array))

## Max
print('max element is ',np.max(normal_array))

## Sum 
print('Sum of element is ',np.sum(normal_array))

## Mean 
print('mean of element is ',np.mean(normal_array))

## Median 
print('median of  element is ',np.median(normal_array))

## Std
print('Standard of element is ',np.std(normal_array))

array is [0 1 2 3 4 5 6 7 8 9]
min element is  0
max element is  9
Sum of element is  45
mean of element is  4.5
median of  element is  4.5
Standard of element is  2.8722813232690143
